### ISSUE TITLE
-d parameter / decryption not working

### ISSUE THREAD

**Issue by supagusti** [ric-geek/dlms-encrypt-decrypt-cli#1]
Excuse me, but i'm fiddeling arount to get data out of my smartmeter and the data is encrypted. 
The best program I found is your DLMS-APDU Encrypter-Decrypter. But I cannot reproduce the dlms_cli -d command from your readme.md. It seems like the code is missing from your programm. It is parsing the command line parameters key (line 64) enc (line69) and auth (line77) but the dec parameter is missing.

Maybe you can update the code so I can use it?

**Comment by ric-geek** [comment]
Hi, i fixed the error.
Now it should work

**Comment by supagusti** [comment]
Thank you!
